# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52010400ca7037f7f95e703f83d9c2f84b0480eea4e6c848c618d869624a59fb1a20c5ca0651eafc3479b6772a011a98e1c793adb6659d16549f0703c665c20a

test:
  secret_key_base: 7679953ff140e7a390367f571d6410e3bab46da2a6a6a7e53810b7444ade1dd35b28ecce22c2642e93d4fb758f43dbdf515708e01ab36e5836f5f27da9a54143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>